---
# tasks file for kubernetes
- name: Disable swap in all nodes
  hosts: ansible
  vars_files: 
  - package.yml
  tasks:
   - name: Disable swap
     shell: swapoff -a
   - name: edit fstab file to change the swap partition
     shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
   - name: Load the required kernel modules on all nodes
     shell: tee /etc/modules-load.d/containerd.conf <<EOF
            overlay
            br_netfilter
            EOF
   - name: reload the modprobe
     shell: modprobe overlay br_netfilter
   - name: Configure the critical kernel parameters for Kubernetes using the following
     shell: tee /etc/sysctl.d/kubernetes.conf <<EOF
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward = 1
            EOF
   - name: reload the require changes
     shell: sysctl --system
    
   - name: Install containerd Runtime
     apt:
      name: "{{ packages }}"
      state: present
     become: yes
   - name: enable docker repository
     shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg
   - name: add repository
     shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    

