---
# tasks file for kubernetes
- name: Disable swap in all nodes
  hosts: ansible
  vars_files: 
  - package.yml
  tasks:
   - name: Disable swap
     shell: swapoff -a
   - name: edit fstab file to change the swap partition
     shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
   - name: Load the required kernel modules on all nodes
     shell: tee /etc/modules-load.d/containerd.conf <<EOF
            overlay
            br_netfilter
            EOF
   - name: reload the modprobe
     shell: modprobe overlay br_netfilter
   - name: Configure the critical kernel parameters for Kubernetes using the following
     shell: tee /etc/sysctl.d/kubernetes.conf <<EOF
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward = 1
            EOF
   - name: reload the require changes
     shell: sysctl --system
    
   - name: Install containerd Runtime
     apt:
       name: "{{ packages }}"
       state: present
     become: yes
   - name: enable docker repository
     shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg
   - name: add docker repository
     apt_repository: 
       repo:  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
       state: present
       update_cache: true
  #  - name: enable docker repository
  #    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg
  #  - name: add repository
  #    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    #  apt_key:
    #   url: https://download.docker.com/linux/ubuntu/gpg
    #   state: present
    #  register: add_repository_key
    #  ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"
   - name: update and install containerd
     apt:
       update_cache: true
         #upgrade: "full"  
   - name: Install containerd
     apt: 
      name: containerd.io
      state: present
   - name: Configure containerd to start using systemd as cgroup 
     shell: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
            sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
   - name: Restart and enable the containerd service
     shell: sudo systemctl restart containerd 
            sudo systemctl enable containerd
   - name: Add kubernetes repository for all nodes
     shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/kubernetes-xenial.gpg
   - name: enable kubernetes repository 
     apt_repository:
       repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
       state: present
       update_cache: true
   - name: Install iubectl, Kubeadm and kubelet
     apt: 
      name: kubelet kubeadm kubectl
      state: present
      update_cache: true

    

